Repository astercapital/airless, pull requests merged in 2025-05, with the labels that each got.

#107 Bugfix/event id as int
  packages/airless-core/.bumpversion.cfg
  packages/airless-core/CHANGELOG.md
  packages/airless-core/airless/core/hook/datalake.py
  packages/airless-core/pyproject.toml
  packages/airless-google-cloud-storage/.bumpversion.cfg
  packages/airless-google-cloud-storage/CHANGELOG.md
  packages/airless-google-cloud-storage/pyproject.toml
  packages/airless-google-cloud-storage/requirements.txt
Labels: bug

#108 Refactor/airless email secret
  packages/airless-email/.bumpversion.cfg
  packages/airless-email/CHANGELOG.md
  packages/airless-email/airless/email/hook/email.py
  packages/airless-email/pyproject.toml
  packages/airless-email/requirements.txt
Labels: refactor

#110 minor changes in READMEs
  README.md
  mkdocs.yaml
  packages/airless-google-cloud-secret-manager/README.md
  packages/airless-slack/README.md
Labels: bug, feature

#111 Bugfix error handling in GCP airless-slack
  packages/airless-slack/.bumpversion.cfg
  packages/airless-slack/CHANGELOG.md
  packages/airless-slack/airless/slack/operator/__init__.py
  packages/airless-slack/airless/slack/operator/google.py
  packages/airless-slack/airless/slack/operator/slack.py
  packages/airless-slack/pyproject.toml
  packages/airless-slack/requirements.txt
Labels: bug

#112 Feature/pubsub default serializer
  packages/airless-google-cloud-core/.bumpversion.cfg
  packages/airless-google-cloud-core/CHANGELOG.md
  packages/airless-google-cloud-core/airless/google/cloud/pubsub/hook/pubsub.py
  packages/airless-google-cloud-core/pyproject.toml
Labels: feature

#118 Here's what I did to add Google-style docstrings to your Python files:
  packages/airless-captcha/airless/captcha/providers/two_captcha.py
  packages/airless-core/airless/core/hook/llm.py
  packages/airless-google-cloud-bigquery/airless/google/cloud/bigquery/hook/bigquery.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/operator/storage.py
  packages/airless-google-cloud-vertexai/airless/google/cloud/vertexai/hook/gemini.py
Labels: enhance
