Repository astercapital/airless, pull requests merged in 2025-04, with the labels that each got.

#92 Feature add some logs
  packages/airless-google-cloud-core/airless/google/cloud/core/operator/error.py
Labels: feature

#93 Release airless google cloud core v0 0 5
  packages/airless-google-cloud-core/.bumpversion.cfg
  packages/airless-google-cloud-core/CHANGELOG.md
  packages/airless-google-cloud-core/pyproject.toml
Labels: release

#95 Bugfix secret manager `get_secret` method call
  packages/airless-email/CHANGELOG.md
  packages/airless-email/airless/email/hook/email.py
  packages/airless-slack/CHANGELOG.md
  packages/airless-slack/airless/slack/operator/slack.py
Labels: bug

#97 [airless-slack] Bump version: 0.0.4 → 0.0.5
  packages/airless-slack/.bumpversion.cfg
  packages/airless-slack/CHANGELOG.md
  packages/airless-slack/pyproject.toml
Labels: bug

#96 [airless-email] Bump version: 0.0.5 → 0.0.6
  packages/airless-email/.bumpversion.cfg
  packages/airless-email/CHANGELOG.md
  packages/airless-email/pyproject.toml
Labels: bug

#98 Remove debug print statement in redirect operator
  packages/airless-core/airless/core/operator/redirect.py
Labels: bug

#99 Bugfix/google cloud storage operators rollback
  packages/airless-google-cloud-storage/CHANGELOG.md
  packages/airless-google-cloud-storage/airless/google/cloud/storage/operator/storage.py
Labels: bug

#102 Feature/google error operator save to datalake
  .gitignore
  packages/airless-core/.bumpversion.cfg
  packages/airless-core/CHANGELOG.md
  packages/airless-core/airless/core/hook/datalake.py
  packages/airless-core/pyproject.toml
  packages/airless-core/tests/core/hook/test_datalake.py
  packages/airless-google-cloud-core/.bumpversion.cfg
  packages/airless-google-cloud-core/CHANGELOG.md
  packages/airless-google-cloud-core/airless/google/cloud/core/operator/__init__.py
  packages/airless-google-cloud-core/airless/google/cloud/core/operator/error.py
  packages/airless-google-cloud-core/pyproject.toml
  packages/airless-google-cloud-core/requirements.txt
  packages/airless-google-cloud-storage/.bumpversion.cfg
  packages/airless-google-cloud-storage/CHANGELOG.md
  packages/airless-google-cloud-storage/airless/google/cloud/storage/hook/__init__.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/hook/datalake.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/hook/storage.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/operator/__init__.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/operator/error.py
  packages/airless-google-cloud-storage/pyproject.toml
  packages/airless-google-cloud-storage/requirements.txt
  requirements-dev.txt
Labels: feature

#103 Release/update airless core 0.2.1
  packages/airless-captcha/.bumpversion.cfg
  packages/airless-captcha/CHANGELOG.md
  packages/airless-captcha/pyproject.toml
  packages/airless-captcha/requirements.txt
  packages/airless-email/.bumpversion.cfg
  packages/airless-email/CHANGELOG.md
  packages/airless-email/pyproject.toml
  packages/airless-email/requirements.txt
  packages/airless-google-cloud-bigquery/.bumpversion.cfg
  packages/airless-google-cloud-bigquery/CHANGELOG.md
  packages/airless-google-cloud-bigquery/pyproject.toml
  packages/airless-google-cloud-bigquery/requirements.txt
  packages/airless-google-cloud-secret-manager/.bumpversion.cfg
  packages/airless-google-cloud-secret-manager/CHANGELOG.md
  packages/airless-google-cloud-secret-manager/pyproject.toml
  packages/airless-google-cloud-secret-manager/requirements.txt
  packages/airless-google-cloud-vertexai/.bumpversion.cfg
  packages/airless-google-cloud-vertexai/CHANGELOG.md
  packages/airless-google-cloud-vertexai/pyproject.toml
  packages/airless-google-cloud-vertexai/requirements.txt
  packages/airless-pdf/.bumpversion.cfg
  packages/airless-pdf/CHANGELOG.md
  packages/airless-pdf/pyproject.toml
  packages/airless-pdf/requirements.txt
  packages/airless-slack/.bumpversion.cfg
  packages/airless-slack/CHANGELOG.md
  packages/airless-slack/pyproject.toml
  packages/airless-slack/requirements.txt
Labels: release

#104 Bugfix/error project
  packages/airless-core/.bumpversion.cfg
  packages/airless-core/CHANGELOG.md
  packages/airless-core/airless/core/operator/error.py
  packages/airless-core/pyproject.toml
Labels: bug

#105 Refactor/avoid error infinite loop
  packages/airless-core/.bumpversion.cfg
  packages/airless-core/CHANGELOG.md
  packages/airless-core/airless/core/operator/error.py
  packages/airless-core/pyproject.toml
  packages/airless-core/tests/core/operator/test_error.py
Labels: refactor

#106 Feature/release unused memory from parquet
  packages/airless-core/.bumpversion.cfg
  packages/airless-core/CHANGELOG.md
  packages/airless-core/airless/core/hook/datalake.py
  packages/airless-core/airless/core/hook/file.py
  packages/airless-core/pyproject.toml
  packages/airless-core/tests/core/hook/test_datalake.py
  packages/airless-core/tests/core/hook/test_file.py
  packages/airless-google-cloud-storage/.bumpversion.cfg
  packages/airless-google-cloud-storage/CHANGELOG.md
  packages/airless-google-cloud-storage/airless/google/cloud/storage/hook/datalake.py
  packages/airless-google-cloud-storage/airless/google/cloud/storage/hook/storage.py
  packages/airless-google-cloud-storage/pyproject.toml
  packages/airless-google-cloud-storage/requirements.txt
Labels: feature
